install:
  - appveyor DownloadFile https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0/jruby-bin-9.0.0.0.zip
  - 7z x jruby-bin-9.0.0.0.zip -y > nul
  - SET PATH=C:\projects\shoes4\jruby-9.0.0.0\bin;%PATH%
  - gem install bundler
  - bundle

build: off
shallow_clone: true
test_script:
  - rake spec:shoes
